### ISSUE TITLE
Non-Alphanumeric Scene Names Not Supported

### ISSUE THREAD

**Issue by mxashlynn** [LemmaEOF/GBSToolkit#1]
It looks like the tool assumes all scene names will be valid folder/directory names on the host OS.
Specifically, on Windows 10 and Python 3.7 on my Yurivania 1 project, I get the following errors:
`NotADirectoryError: [WinError 267]`

A number of my Scene Names are not valid Windows directory names.

I haven't used python in a while, but I will try to fix this if I have time later today.

Thanks for making this cool tool!  😄

**Comment by LemmaEOF** [comment]
...oh my god lmao I sanitize actor/trigger names because I have non-alphanumerics but I *completely* forgot to do it for scene names too

**Comment by mxashlynn** [comment]
Well, with your tip that was very easy and quick to fix!
I might go back later and make this sanitization routine into a dedicated function with a few more details, if you think that is warranted.
